name: Deploy Landing                                                                                                     
on:                                                                                                                      
    push:                                                                                                                  
      branches:                                                                                                            
        - main                                                                                                             
                                                                                                                           
jobs:                                                                                                                    
    deploy:                                                                                                                
      runs-on: ubuntu-latest                                                                                               
      steps:                                                                                                               
        - name: Deploy to Server via SSH                                                                                   
          uses: appleboy/ssh-action@master                                                                                 
          with:                                                                                                            
            host: ${{ secrets.REMOTE_HOST }}                                                                               
            username: ${{ secrets.REMOTE_USER }}                                                                           
            key: ${{ secrets.SSH_PRIVATE_KEY }}                                                                            
            script: |                                                                                                      
              cd /var/www/html                                                                                             
              sudo git config --global --add safe.directory /var/www/html
              sudo git reset --hard HEAD
              sudo git pull origin main                                                                                    
              sudo chown -R www-data:www-data /var/www/html                                                                
                                                            
